# build stage
FROM node:lts AS builder

WORKDIR /usr/src/app

COPY package*.json .

RUN npm install

RUN npm install -g @vue/cli

COPY . .

RUN npm run build

FROM nginx
EXPOSE 3000
COPY ./nginx/default.conf /etc/nginx/conf.d/default.conf
COPY --from=builder /usr/src/app/dist /usr/share/nginx/html
