# docker-compose.yml
version: "3"
services:
  tiltedbot.frontend:
    build:
      dockerfile: Dockerfile
      context: ./client
    ports:
      - "52792:80"
    environment:
      NODE_ENV: production
  tiltedbot.backend:
    build:
      dockerfile: Dockerfile
      context: ./server
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://user:pass@postgres:5432/db
      NODE_ENV: development
      PORT: 3000
    ports:
      - "52791:3000"
    volumes:
      - ./server:/usr/src/app
      - /app/node_modules

  tiltedbot.db:
    image: postgres:10.4
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: db
    volumes:
      - ./postgresql/data:/var/lib/postgresql/data
