# docker-compose.yml
version: "3"
services:
  tb_frontend:
    container_name: tb_frontend
    build:
      context: ./client
      dockerfile: Dockerfile.prod
    environment:
      - NODE_ENV=production
    volumes:
      - ./client:/usr/src/app
      - /usr/src/app/node_modules
      - ./logs/npm:/root/.npm/_logs
    depends_on:
      - tb_backend
      - postgresql
  tb_nginx:
    container_name: tb_nginx
    depends_on:
      - tb_backend
      - tb_frontend
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - "20001:80"
  tb_backend:
    container_name: tb_backend
    build:
      context: ./server
      dockerfile: Dockerfile.prod
    environment:
      - NODE_ENV=production
      - PORT=5000
    ports:
      - "5000:5000"
    volumes:
      - ./server:/usr/src/app
      - /usr/src/app/node_modules
      - ./logs/npm:/root/.npm/_logs
    restart: always
  postgresql:
    container_name: tb_db
    image: postgres:latest
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: tiltedbot
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./postgresql/data:/var/lib/postgresql/data