# docker-compose.yml
version: "3"
services:
  frontend_prod:
    build:
      context: ./client
      dockerfile: Dockerfile.prod
    ports:
      - "3000:8080"
    environment:
      - NODE_ENV="production"
    volumes:
      - ./server:/usr/src/app
      - /usr/src/app/node_modules
      - ./logs/npm:/root/.npm/_logs
    depends_on:
      - backend_prod
      - db_prod
  nginx:
    depends_on:
      - backend_prod
      - frontend_prod
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - "3050:80"
  backend_prod:
    build:
    # build from Dockerfile
      context: ./server
      dockerfile: Dockerfile.prod
    environment:
      - NODE_ENV="production"
      - PORT=3000
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=tiltedbot
      - POSTGRES_PORT=5432
    ports:
      - "3005:3005"
    volumes:
      - ./server:/usr/src/app
      - /usr/src/app/node_modules
      - ./logs/npm:/root/.npm/_logs
  db_prod:
    image: postgres:10.4
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=tiltedbot
    volumes:
      - ./postgresql/data:/var/lib/postgresql/data
