# docker-compose.yml
version: "3"

services:
  frontend:
    hostname: frontend
    container_name: tb_frontend
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    ports:
      - "3000:8080"
    environment:
      - NODE_ENV="development"
    volumes:
      - ./client:/usr/src/app
      - /usr/src/app/node_modules
      - ./logs/npm:/root/.npm/_logs
    depends_on:
      - backend
      - postgresql
  backend:
    hostname: tb_backend
    container_name: tb_backend
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    environment:
      - NODE_ENV=development
      - PORT=3000
    ports:
      - "3005:3005"
    volumes:
      - ./server:/usr/src/app
      - /usr/src/app/node_modules
      - ./logs/npm:/root/.npm/_logs
  postgresql:
    hostname: tb_db
    container_name: tb_db

    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: tiltedbot
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./postgresql/data:/var/lib/postgresql/data
