FROM node:alpine

RUN apk add --update --no-cache make g++ jpeg-dev cairo-dev giflib-dev pango-dev libtool autoconf automake

WORKDIR /usr/src/app

COPY ./package*.json .

RUN npm i -G nodemon



RUN npm install

COPY . .

CMD ["npm", "run", "dev"]

EXPOSE 3005